### ISSUE TITLE
Women's tennis?

### ISSUE THREAD

**Issue by jtr13** [mcekovic/tennis-crystal-ball#333] opened 2019-09-20 20:12 UTC
Would be great to have these stats on women's tennis as well.

**Comment by mcekovic** [comment] 2019-09-25 08:35
Woman's tennis would be great, but not enough free time :(.

**Comment by mcekovic** [comment] 2019-09-25 08:35
Duplicate of #289

**Closed by mcekovic** 2019-09-25 08:35 UTC
Labels: duplicate

**Comment by jtr13** [comment] 2019-09-25 11:53
Get it, glad it's on the radar. I'd recommend making it more explicit though that it's a men's tennis site, as simple as adding one word here: "Welcome to Ultimate Tennis Statistics, the ultimate **men's** tennis statistics destination for the die-hard tennis fans!"

I spent some time looking for the women's stats. Great site, thanks for your work on it!
